### PR TITLE
Added futhark lsp

### PR DESCRIPTION
**Pull request by Alexnortung**

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Could you please add this server to the nvim-lsp `all-servers` test case ?

**Comment by GaetanLepage** [comment]
I added the test but it seems that `futhark` is currently broken on nixpkgs.
Hence, I suggest that we wait for it to be fixed before merging.

**Comment by Alexnortung** [comment]
> I added the test

Thanks!

> `futhark` is currently broken on nixpkgs

Where do you find that? I can run it just fine locally and checking `mkDerivation` function on nixpkgs, i can't find anywhere it says broken.
Also the tests seem to pass after updating the nixpkgs input, so it may be that futhark was broken in an earlier version?

**Comment by GaetanLepage** [comment]
> Where do you find that? I can run it just fine locally and checking `mkDerivation` function on nixpkgs, i can't find anywhere it says broken.
> Also the tests seem to pass after updating the nixpkgs input, so it may be that futhark was broken in an earlier version?

Yes it was failing in the previous version of nixos-unstable but now it seems fine !
Maybe, just re-organize the commits to have
1. One that updates the flake inputs
2. A second one that adds the LSP server

**Comment by Alexnortung** [comment]
That should do it :D

**Review by GaetanLepage — APPROVED** [review]

**Comment by GaetanLepage** [comment]
Merged ! Thank you @Alexnortung :)

**Pull request merged**
