### PR TITLE
Followup fixes for #129

### PR DESCRIPTION
**Pull request by PhotonQuantum**
PR #129 broke the helper wrapper and the bufferline plugin support. This PR fixes them.

### CODE REVIEW

**Comment by pta2002** [comment]
I've fixed this in the meantime so I won't be merging it, but thank you anyway :)

**Comment by PhotonQuantum** [comment]
It seems that 
https://github.com/pta2002/nixvim/blob/8d41514bbef2b5ee213c22c70b39e8c976d6200a/wrappers/_shared.nix#L14 hasn't been fixed.

```
error: undefined variable 'pkgs'

       at /nix/store/ihakrpl6f8wqwg4rv310x2zr6zq78kzg-source/wrappers/_shared.nix:14:56:

           13|     description = "Use this option to access the helpers";
           14|     default = import ../plugins/helpers.nix { inherit (pkgs) lib; };
             |                                                        ^
           15|   };
```

**Comment by pta2002** [comment]
oh! sorry

**Comment by PhotonQuantum** [comment]
Rebased this PR on the latest commit.

**Review by pta2002 — APPROVED** [review]

**Pull request merged**
