### PR TITLE
add: added statix, deadnix, nixpkgs_fmt to null-ls sources

### PR DESCRIPTION
**Pull request by Tanish2002**

### CODE REVIEW

**Comment by GaetanLepage** [comment]
Could you please add those sources to the test please ?

**Comment by Tanish2002** [comment]
I don't see any of the null-ls source in test..
Do I just add them in this file? 
https://github.com/pta2002/nixvim/blob/main/tests/test-sources/plugins/null-ls.nix

**Comment by GaetanLepage** [comment]
> Could you please add those sources to the test ?

Let's wait for #374 to get merged.

**Comment by GaetanLepage** [comment]
> Let's wait for #374 to get merged.

Done. You can now rebase on `main` and add your tests :)

**Review by GaetanLepage — APPROVED** [review]
LGTM !

**Comment by Tanish2002** [comment]
didn't run the `nix flake check` as I was running out of disk-space :laughing:. Let's wait for the pipeline to complete before merge

**Pull request merged**
