### PR TITLE
add bufferline and nvim-lsp/pyright

### PR DESCRIPTION
**Pull request by Builditluc**
I've added the plugin bufferline and nvim-lsp/pyright and the capabilities option for nvim-lsp (will use that later for cmp-nvim)

### CODE REVIEW

**Comment by Builditluc** [comment]
I've also added comment-nvim (another Neovim comment plugin)

**Comment by pta2002** [comment]
Hey, this looks great! Just a thing I'd change though: the default on the options should be, in most cases, null, so that we're not filling up the config with needless variable declarations. I can change that, if you want. I have the `helpers.mkPlugin` interface to help with this, which should work for most plugins that only need to define options as global variables.

**Comment by Builditluc** [comment]
Okay, I'll change that

**Comment by Builditluc** [comment]
All of the options are now null by default

**Review by pta2002 — APPROVED** [review]
Looks good!

**Pull request merged**
