### PR TITLE
added nord colorscheme

### PR DESCRIPTION
**Pull request by Alexnortung**
This PR adds the nord colorscheme as a module with the [`nord-nvim`](https://github.com/shaunsingh/nord.nvim) package

### CODE REVIEW

**Comment by Alexnortung** [comment]
Actually there is an issue with this PR.
The options don't really work since they need to be set before calling `colorscheme nord`. Is there a way we can do this?

**Comment by pta2002** [comment]
Hm, I think you can change nixvim.nix to add the colorscheme call after Lua
- I don't think that'll cause an issue with anything else so I say you can
do it, probably for the best too

A quarta, 13/07/2022, 17:22, Alexander Nortung ***@***.***>
escreveu:

**Comment by Alexnortung** [comment]
I have changed it now and it works with my current config :)

**Comment by pta2002** [comment]
Looks good, thanks!

**Pull request merged**
