### PR TITLE
plugins/catppuccin: add colorscheme + test

### PR DESCRIPTION
**Pull request by Tanish2002**
Added the catppuccin colorscheme (https://github.com/catppuccin/nvim)

### CODE REVIEW

**Review by GaetanLepage — CHANGES_REQUESTED** [review]
Very good !
I personally prefer when the option declarations are spaced (1 blank line between each).
Besides that, I have nothing to say, good job :)

**Comment by GaetanLepage** [comment]
Seems like the pipeline is failing.
Be sure to
```sh
# Format the code
nix fmt

# Run the tests
nix flake check
```

**Comment by GaetanLepage** [comment]
I pushed to your branch to do a little bit of formatting.
I changed the type of the `customHighlights` option to be either an `attrsOf attrs` or a `str` (the code of a lua function).
The implementation part for this is lacking.

**Comment by Tanish2002** [comment]
I believe we could just simply do a `str` for a lua function and add a example in the description.
Otherwise do you have a idea for implementing this :thinking:

**Comment by GaetanLepage** [comment]
> @GaetanLepage I tried to implement the `customHighlights` option such that it can be a `str` or a `attrsOf attrs`. I believe it works.

This implementation looks good to me.
The only issue is the `@` prefix of the keys of the attrs.
Indeed, they will be ignored by nixvim when being translated to lua:
https://github.com/pta2002/nixvim/blob/3600698abad00756947eb3a3d837beedf1c2f551/lib/helpers.nix#L22-L23

I doubt that it would work... But the user can always fall back on a custom function declaration.

**Comment by Tanish2002** [comment]
yeah, for complex configs the user could fallback to the string.
Do I need to work on anything else?

**Comment by GaetanLepage** [comment]
> yeah, for complex configs the user could fallback to the string. Do I need to work on anything else?

No, I think that it is alright like this

**Review by GaetanLepage — APPROVED** [review]
Approved

**Pull request merged**
